# Generated by Django 5.1.7 on 2025-04-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contact_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
