# Generated by Django 5.1.7 on 2025-04-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactus_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contact_image',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
