# Generated by Django 5.1.7 on 2025-04-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contactus_contact_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='contact_image',
            new_name='image',
        ),
    ]
