# Generated by Django 5.1.7 on 2025-04-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_rename_contact_image_contactus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
