# Generated by Django 5.1.7 on 2025-04-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contactus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='image',
        ),
    ]
