# Generated by Django 5.1.7 on 2025-04-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_location', models.TextField()),
                ('icon_name', models.CharField(max_length=100)),
                ('ser_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
