# Generated by Django 5.1.7 on 2025-04-21 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_room_students_data_is_active_students_data_room'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('room', 'Room'), ('bathroom', 'Bathroom'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=100)),
                ('other_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('room_number', models.CharField(max_length=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.students_data')),
            ],
        ),
    ]
