# Generated by Django 5.1.7 on 2025-04-14 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_students_data_course_students_data_enrollmentyear_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_data',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students_data',
            name='name',
        ),
        migrations.RemoveField(
            model_name='students_data',
            name='password',
        ),
        migrations.RemoveField(
            model_name='students_data',
            name='username',
        ),
        migrations.AddField(
            model_name='students_data',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
